spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/agrovetdb?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2

spring.datasource.username=42oKh5PedS8RcwF.root
spring.datasource.password=S1b72DGkNuiXrehj

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true